<a href="https://colab.research.google.com/github/onleey/python_demo/blob/master/200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- NumPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.


공식문서 https://numpy.org/doc/stable/  
numpy 100 문제 https://github.com/rougier/numpy-100

# 1. 데이터 생성

In [14]:
import numpy as np

np.zeros( ) 생성할 개수 삽입 . zero라 0이 값.

In [15]:
a = np.zeros(3) #1차원 배열 생성 (벡터)
a

array([0., 0., 0.])

In [16]:
print(a)

[0. 0. 0.]


In [17]:
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [18]:
print(a.__repr__)
print(a.__str__)

<method-wrapper '__repr__' of numpy.ndarray object at 0x799c883aaf10>
<method-wrapper '__str__' of numpy.ndarray object at 0x799c883aaf10>


In [19]:
print(type(a))

<class 'numpy.ndarray'>


np.array()



In [20]:
a = np.array([1,2,3])   # 1차원 배열 =벡터
a

array([1, 2, 3])

In [21]:
print(a)
print(type(a))
print(dir(a))

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'

In [22]:
#2차원 배열 = 행렬
b = np.array([[1,2],[3,4]])   #2행 2열
b

array([[1, 2],
       [3, 4]])

In [23]:
print(b)
print(type(b))
print(dir(b))
print(b.shape)   #.shape 현재 몇행 몇렬인지 알고싶다.

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__

In [24]:
# 3차월 배열 , 그이상은 텐서(tensor)라고 함
c = np. array([[[1,2],[3,4]],[[5,6],[7,8]]])  #2층(면,공간), 2행, 2열
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
print(c)
print(type(c))
print(dir(c))
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__po

In [26]:
a = np.array ([1,2,3])
print(a)
print(a[0])

[1 2 3]
1


In [27]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 출력된다.
# numpy는homogenous이다. 즉, 같은 타입만 저장 할 수 있다.
a = np.array ([1,'2',3])
print(a)
print(a[0])

['1' '2' '3']
1


In [28]:
#논리값에서 False는 0, True는 1로 저장함
a = np.array ([0,False,1,True])
print(a)
print(a[0])

[0 0 1 1]
0



#np.zeros
```
-tuple로 인자를 넣으면 그대로 모양을 만든다.   
- (2,3): 2행 3열의 행렬을 만든다.   
- zeros는 기본값으로 0.으로 값을 모두 채운다.
  -np.zeros((2,3))
  -np.zeros([2,3])

```

In [29]:
a = np.zeros(3)

print(a)
print(a.shape)

[0. 0. 0.]
(3,)


In [30]:
a = np.zeros((2,3))

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [31]:
a = np.zeros([2,3])

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


### np.eye
- eye는 단위행렬
- 숫자만 사용할 수 있다.


In [32]:
a= np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬생성
a = np.eye(3,2) #3행 2열
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
# 1이 시작되는 위치를 지정할 수 있다. (k=1)
a= np.eye(3,4,k=1) #3행 4열
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 단위행렬 identity
- 수학에서 단위행렬은 영어로 identity matrix
- 크기 한 개만 지정해서 생성할 수 있다.

In [35]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.full
 - 지정한 크기의 배열을 생성하고 채울값을 지정 한다.

In [36]:
#2행 2열의 행렬을 생성하고 1로 초기화 해준다.
a = np.full((3,4),1) #np.full(shape. fill_value)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
#2행 2열의 행렬을 생성하고 각 행마다 1, 2로 초기화 해준다.
a= np.full((2,2),[1,2])
a

array([[1, 2],
       [1, 2]])

In [38]:
# 2행 2열의 행렬을 생성하고 각각 1,2,3,4,로 초기화 해준다.
a= np.full((2,2),[[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.  

In [39]:
a = np.empty(3)
a

array([1., 1., 1.])

In [40]:
# 2행2열이 생성됨
a= np.empty((2,3))
a

array([[1., 0., 0.],
       [1., 0., 0.]])

### np.ones
 - 배열의 모든 값을 1로 채운다.


In [41]:
a = np.ones(3)
a

array([1., 1., 1.])

In [42]:
a = np.ones((2,3))
a


array([[1., 1., 1.],
       [1., 1., 1.]])

### _like
- _like가 붙으면 shape가 같게 만들어 진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.


In [43]:
# 2행 3열의 배열 생성

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
b = np.ones_like(a) # a배열의 shape를 복사한다.
b

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
c = a+b
c

array([[2, 3, 4],
       [5, 6, 7]])

### linespace
- 동등한 간격으로 값을 생성한다.
- 0부터 49까지 50개가 생성된다면 세번째 num 인자 값이 생략되어 있으므로 start와
  end 계산해서 default 50이 생성된다.
- linspace(start, end, num)
- linspace (0,49) # 50 #num의 default value 50



In [46]:
a = np.linspace(0,49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [47]:
#endpoint를 False로 설정을 하면 5가 포함이 안된다.
a = np.linspace(0, 5, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

## logspace
-linspace와 비슷하다.   
-log scale을 사용하는 차이가 있다.   

In [48]:
np.logspace(1,50,30) #1부터 50까지 사이의 30개의 요소를 생성한다.

array([1.00000000e+01, 4.89390092e+02, 2.39502662e+04, 1.17210230e+06,
       5.73615251e+07, 2.80721620e+09, 1.37382380e+11, 6.72335754e+12,
       3.29034456e+14, 1.61026203e+16, 7.88046282e+17, 3.85662042e+19,
       1.88739182e+21, 9.23670857e+22, 4.52035366e+24, 2.21221629e+26,
       1.08263673e+28, 5.29831691e+29, 2.59294380e+31, 1.26896100e+33,
       6.21016942e+34, 3.03919538e+36, 1.48735211e+38, 7.27895384e+39,
       3.56224789e+41, 1.74332882e+43, 8.53167852e+44, 4.17531894e+46,
       2.04335972e+48, 1.00000000e+50])

##데이터타입

In [49]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [50]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [51]:
b = np.array([1,2,3], dtype=np.int8) # -128~ +127까지만 허용이 된다.
b

array([1, 2, 3], dtype=int8)

In [52]:
b = np.array([-128,-127,5,100,127], dtype=np.int8)
b

array([-128, -127,    5,  100,  127], dtype=int8)

In [53]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
b = np.array([-128,-127,5,100,128], dtype=np.int8)
b

array([-128, -127,    5,  100, -128], dtype=int8)

In [54]:
#np.int8은 -128~127 사이의 값을 저장할 수 있다.
#128이 -128로 저장된다. (쓰레기 값)
b = np.array([-128,-127,5,100,128], dtype=np.int8)
b

array([-128, -127,    5,  100, -128], dtype=int8)

In [55]:
#python의int를 지정한다.
c= np.array([127,2,3,-128],dtype=int)  #int는 python의 데이터타입이다.
c

array([ 127,    2,    3, -128])

In [56]:
print(c.dtype)            #python의 int == numpy의 64
print(type(c))

int64
<class 'numpy.ndarray'>


# python의 도움말

In [57]:
sum?

In [58]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



#numpy 도움말

In [59]:
# np.lookfor('sum')

In [60]:
a = np.array([[1,2,3],[4,5,6]])
# array의 shape를 알려준다.
a.shape    #(2,3)은 2행 3열이라는 뜻

(2, 3)

In [61]:
# array이 몇차원인지 알려준다.
a.ndim # ndim 은 몇차원인지를 알려줌

2

In [62]:
a.dtype  # array배열의 타입을 알수있다.

dtype('int64')

In [63]:
a.size   #요소개수를 알려준다.
        #shape로도 알수있다.

6

In [64]:
# 요소당 byte수를 알려준다.
a.itemsize   #8bit = 1byte   / 64bit = 8 byte

8

## numpy 와 python의 속도차이

In [65]:
np.arange(10)  # ([start,] end, [step]) 1,3은 생략가능 range랑 동일

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#num을 이용한 계산
%time np.sum(np.arange(1000000000))

CPU times: user 1.34 s, sys: 2.33 s, total: 3.67 s
Wall time: 3.69 s


499999999500000000

In [67]:
#python을 이용한 계산
%time sum(range(1000000000))

CPU times: user 27.3 s, sys: 151 ms, total: 27.5 s
Wall time: 32.8 s


499999999500000000

같은 np.sum()을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.


In [68]:
%time np.sum(np.arange(1000000000))

CPU times: user 1.72 s, sys: 1.68 s, total: 3.39 s
Wall time: 4.6 s


499999999500000000

In [69]:
%time np.sum(range(100000000))

CPU times: user 14.1 s, sys: 2.64 s, total: 16.7 s
Wall time: 21.9 s


4999999950000000

## copy

 ※ 대입문 6가지
 a = 1
 a = b = 1
 a,*b = 1,2,3 #튜플 할당
 a += 1
 global , nolocal

#python 에서 copy

In [70]:
a= [1,2,3] #list

In [71]:
b =a

In [72]:
b

[1, 2, 3]

In [73]:
a is b

True

In [74]:
# a와 b가 메모리 공유
# b값을 변경하면 a도 같이 변경된다
b[0] = 7

In [75]:
print(b)
print(a)

[7, 2, 3]
[7, 2, 3]


1차원일때 copy

In [76]:
 a = [1,2,3]


In [77]:
# copy()는 똑같은 값만 가지고 메모리는 공유하지 않는다. 즉 deep copy가 된다.
b = a.copy()

In [78]:
a is b

False

In [79]:
id(a)

133714056675904

In [80]:
id(b)

133713210454016

In [81]:
a == b  #값 비교


True

In [82]:
b[0]= 8

print(a)
print(b)

[1, 2, 3]
[8, 2, 3]


In [83]:
print(a is b)
print (a == b)

False
False


list가 2차원 일때 copy

In [84]:
a = [[1,2,3]]

In [85]:
type(a)

list

In [86]:
# shallow copy (얕은 카피 )
b=a.copy()

In [87]:
print (a is b)
print (a == b)

False
True


In [88]:
print(a[0])
print(b[0])

[1, 2, 3]
[1, 2, 3]


In [89]:
b[0][0] = 10

In [90]:
print(a[0])
print(b[0])

[10, 2, 3]
[10, 2, 3]


In [91]:
print(a[0] == b[0])
print(a[0] is b[0])

True
True


In [92]:
import copy

In [93]:
a = [[1,2,3]]
b = copy.deepcopy(a) # list가 2차원 일 때, deep copy를 하기 위해서 copy 모듈에 있는 deepcopy 메소드를 사용한다.

In [94]:
print (a is b)  #메모리 주소
print (a == b)  # 값 주소

False
True


In [95]:
b[0][0] = 10

In [96]:
print(a[0])
print(b[0])

[1, 2, 3]
[10, 2, 3]


In [97]:
print(a[0] == b[0])
print(a[0] is b[0])

False
False


[:] 는 전체라는 뜻이다.   
슬라이싱 방식으로 1차 리스트 일때는 재할당 하면 deep copy가 발생된다.   
슬라이싱 방식으로 2차 리스트 이상인 경우는 shallow copy가 발생된다.  

In [98]:
a = [1,2,3]
b= a[:]

print (a is b)
print (a == b )

a = [[1,2,3]]
b = a[:]
print (a is b)
print (a == b)

False
True
False
True


In [99]:
m= 100
n= m
print (m is n )
print (m == n )

True
True


In [100]:
a = 256
b = 256

a is b   # True

a = 257
b = 257

a is b    #False

False

In [101]:
 a = [257,2,3]
 b = a[:]    # a[:] = a.copy()와 같다

 print( a == b )
 print(a is b )


print(id(a))
print(id(b))
print(a[0] == b[0])
print(a[0] is b[0])

True
False
133713207663808
133714056675904
True
True


In [102]:
# intering 기법
# 파이썬은 느리기 때문에 중간에 cache 저장하는 기법이 있다.
# -5에서 256은 파이썬에서 같은 메모리 주소를 사용한다. (interning 기법)
# 문자열에서 a-zA-Z0-9는 내부적으로 interning 기법을 사용한다. (한글은 무조건 다른메모리를 사용함.)
# is 는 값을 비교

m= 256
n = 256
print (m is n )      ## -5 ~ 256 까지는 같은 메모리를 쓰기때문에 같다

m=257
n=257
print(m is n )       ## 257 이기 때문에 각각 다른 메모리를 써서 False

k = 'python3_파이썬'
p = 'python3_파이썬'  # 한글은 다른 메모리를 사용함 False 한글빼면 True

print(k is p)

True
False
False


In [103]:
a = [[1,2,3],[4,5,6]]
b = a

print( a is b)
print (a == b)


True
True


In [104]:
c = a.copy()

print(a is c)
print( a == c)

a[0][0] = 20
print( a is c)
print(a == c)

False
True
False
True


numpy의 copy

In [105]:
import copy

d = copy. deepcopy(a)


d[0][0] = 30

print(d is a)   ## is는 주소비교
print(d == a)   ## ==는 값 비교

print(d[0] is a[0])
print(d[0] == a[0])

print(d[0][0] is a[0][0])
print(d[0][0] == a[0][0])

print(d[1] is a[1])
print(d[1] == a[1])

False
False
False
False
False
False
False
True


In [106]:
a = b = np.array([1,2,3])


In [107]:
print(a is b)
print (a == b)

True
[ True  True  True]


In [108]:
a[0]

1

In [109]:
a[:]

array([1, 2, 3])

In [110]:
a[0] = 100
print(a[0])
print(b[0])

100
100


array는homogeneous, sequence, mutable 이다.  
list는 heterogeneous, sequence, mutable 이다.  

In [111]:
a = np.array([1,2,3])
#numpy는 기본적으로 deepcopy가 발생된다.

b = a.copy()

print(a is b)
print(a == b )


False
[ True  True  True]


### as 계열
다른 데이터 타입을 가져와 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.   


In [112]:
a = [1.5,2.5,3.5]
b = np.array(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [113]:
a = [1.5,2.5,3.5]
b = np.asarray(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))

<class 'list'>
<class 'numpy.ndarray'>
<class 'float'>
<class 'numpy.float64'>


In [114]:
a = [1,2,3]
b = np.asfarray(a)

print(type(a))
print(type(b))
print(type(a[0]))
print(type(b[0]))


<class 'list'>
<class 'numpy.ndarray'>
<class 'int'>
<class 'numpy.float64'>


## 값 가져오기

### (1) 인덱싱, 슬라이싱 방법 가능

In [115]:
a = [[1,2,3],[4,5,6]] # 파이썬 리스트
b = np.array ([[1,2,3],[4,5,6]]) #넘파이의 array (배열)

print(a[0])
print(b[0])

[1, 2, 3]
[1 2 3]


In [116]:
print(type(a[0]))   #리스트
print(type(b[0]))    # 배열

<class 'list'>
<class 'numpy.ndarray'>


In [117]:
#print(a[0,1])
print(a[0][1])
print(b[0,1]) # array일때 인덱스 이렇게 가능함

2
2


In [118]:
print(a[slice(0,1)]) # 0행부터 1행 미만의 데이터를 가져온다.
print(a[0])

print(type(a[slice(0,1)]))
print(type(a[0]))

[[1, 2, 3]]
[1, 2, 3]
<class 'list'>
<class 'list'>


numpy는 기본적으로 인덱싱/슬라이싱할 때 comma를 사용 할 수 있다.  

In [119]:
#numpy

print(type(b))
print(b[0,1])     # b [행,열]   인덱싱
print(b[0][1])    # b [행][열]  인덱싱
print(b[0,-1])    #             인덱싱
print(b[0:1,0:2]) #             슬라이싱 [[1 2]]
print(b[0:2,0:2]) #             [[12][45]]





<class 'numpy.ndarray'>
2
2
3
[[1 2]]
[[1 2]
 [4 5]]


In [120]:
#python
print(type(a))
print(a[0][1])
print(a[0:1])
print(a[0:1 ][0:1])

<class 'list'>
2
[[1, 2, 3]]
[[1, 2, 3]]


(2) boolen indexing



In [121]:
a=[[1,2,3],[4,5,6]]

In [122]:
print(type(a))
print(a*3)
#a>3 은안됨

<class 'list'>
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [123]:
b = np. array([[1,2,3,4]])
c = np. array([[2,2,2,2]])

b>c

array([[False, False,  True,  True]])

array 는 scalar와 연산하면 elementwise로 계산한다.   
(elementswise: 원소별로 각각 계산이 된다.)   

In [124]:
b>2

array([[False, False,  True,  True]])

In [125]:
b[np.array([[False,False,True,True]])]

array([3, 4])

In [126]:
b[b>2]

array([3, 4])

nu에서 boolean indexing조건
 - array만 가능하다.
 -numpy True, False로만 가능하다.
 -shape이 맞아야 한다. (개수가 맞을때만 사용할수있다.)


(3) fancy indexing

In [127]:
#np.arange([start,]end [step])
# reshape(행 갯수, 열갯수) : 배열의 구조변경
a= np.arange(100)
b= a.reshape(20, 5)
print(a.shape)
print(b.shape)

b=np.arange(100).reshape(20,5)
b

(100,)
(20, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [128]:
#print(b[:])  전체를 가져온다 b[:,:]와 같다.
# print(b[1,3])   #b[행,열]   / 인덱싱으로 가지고오면 1차원
# print(b[1:3,2:4]) # 1행부터 3행미만, 2열부터 4열미만의 데이터를 가져온다
print(b[[1,3,5],[0,2,4]])  # 1행 0열 . 3행2열 5행 4열의 데이터를 가져온다
print(b[[1,3,5],])  # 1행 3행 5행의 데이터를 가져온다


print(b[:,[0,2,4]])    #0 열, 2열, 4열의 데이터를 가져온다

[ 5 17 29]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]
 [80 82 84]
 [85 87 89]
 [90 92 94]
 [95 97 99]]


In [129]:
#fancy indexing 주의사항

#print( b[[1,3,4],[0,2,]]) #행과 열의개수를 맞춰야함

# print(b[[:],[1,2,3]])# fancying indexing에서는 슬라이싱 사용할수없음


In [130]:
#broadcast로 처리가 되어서 개수가 다르지만 정상적으로 수행한다.
print(b[[1,3,4,],[0]]) # 자동으로 [0,0,0]으로 인식함(꼭 한자리만되는건 아님)

[ 5 15 20]


In [131]:
#print(b[[0,1,3,4],[0,1]])

In [132]:
m = np.arange(1,13).reshape(2,6)
#n = np.array([[2,2]])
n= np.array([[2,2,2,2,2,2]])

print(m)
print(m.shape)
print(n)
print(n.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[2 2 2 2 2 2]]
(1, 6)


In [133]:
print(m+n)

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]]


## 3차원에서 이상에서 차원구분법

In [134]:
b= np.arange(24).reshape(2,3,4)  #3차원 (2층(면)), 3행 4열
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [135]:
b[0] # 2차원으로 반환

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
b[0][0] # 1차원으로 반환

array([0, 1, 2, 3])

In [137]:
b[1,1]

array([16, 17, 18, 19])

In [138]:
b[0,1,3] # 0공간 1행 3열

7

In [139]:
b[:,1,3] # 모든 공간 1행 3열

array([ 7, 19])

In [140]:
b[:,:,1] # 모든층, 모든 행의 1열

array([[ 1,  5,  9],
       [13, 17, 21]])

In [141]:
m= np.arange(1,9).reshape(2,4)
# n= np.array([2])    #(1,)
# n= np.array([[2]])  #(1,1)

n=np.array([[1,2,3,4]])  #(1,4)
# n=np.array([1,2,3,4]) #(4,)
n=np.array([[1],[2]])   #(2,1)


print(m)
print(m.shape)
print(n)
print(n.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]]
(2, 1)


###fancy indexing 과 indexing 차이
- indexing은 원래차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.  

-

In [142]:
#indexing은 차원이 하나 감소해서 가져온다 (3차원을 2차원으로 가져온다.)
b [0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
#fancy indexing은 원래 3차원 그대로 가지고온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [144]:
#b[0]은 b[0,:,:] 의 단축 표현법이다.
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
# b[[0]] b[[0],:,:] 의 단축 표현법이다.
b[[0],:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## Ellipsis
- ...(Ellipsis)는 이후로 모든것을 의미한다.  

In [146]:
#b[0] = b[0,:,:] = b[0,...]
b[0]  #생략기법
b[0,:,:] #slicing 기법
b[0,...] #ellipsis 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
type(...)

ellipsis

In [148]:
#숫자 1,5,9 만 가져온다 .
b [0,:,1]

array([1, 5, 9])

In [149]:
b[[0],:,[1]]

array([[1, 5, 9]])

In [150]:
#숫자 1,3,9,3,7,11 가져오기

In [151]:
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [152]:
# 숫자 4,5,6,7,16,17,18,19 가져오기
b[:,1,:]   # 2차원으로 가져옴

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [153]:
b[:,1:2,:]    #3차원으로 가져옴

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [154]:
# 숫자 3,7,11,15,19,23 가져오기

b[:,:,3]
b[:,:,-1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [155]:
b[:,:,3:4]  #3차원 그대로 가져옴

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [156]:
b[:,:,[3]]  #3차원으로 가져옴

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [157]:
b[...,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

 ## 줄임표현 (...)
  출력해야할 데이터수가 엄청 클때 보이는 ... 은 ellipsis와 다르다  



In [158]:
#out에 나오는 ... 은 단순히 줄임표현이다.
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [159]:
# ... 양쪽으로 출력갯수 지정
np.set_printoptions(edgeitems=6)

In [160]:
np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999])

## 연산
numpy연산의 기본은 두개의 shape가 같아야 한다.


In [161]:
a= np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
b= np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
b.shape

(3, 4)

In [164]:
#같은 위치의 원소끼리 더해준다
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

numpy는 elementwise vectorize 연산을 한다.   
vectorze는 데이터의 연산을 일괄적으로 처리하는 기능이다.   


In [165]:
#python의 list에서 + 연산자는 elementwise가 아니라 list를 확장시킨다. (연결 )

[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [166]:
@np.vectorize

def plus(a,b):
  return a+b

plus([1,2,3],[4,5,6])

array([5, 7, 9])

In [167]:
a = np.arange(6).reshape(2,3)
a


array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
b = np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [169]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [170]:
#python에서 list끼리 *(곱하기)를 할수없다
#[1,2,3] * [4,5,6]

In [171]:
c = np.matrix([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [172]:
type(c)

numpy.matrix

In [173]:
print(c)
c*c

# 1*1 + 2*3 = 7 , 1*2+2*4 = 10
# 3*1 + 4*3 = 15 , 3*2+4*4 = 22

# 1*1 + 2*3 , 1*2+2*4    [[7,10]]
# 3*1 + 4*3 , 3*2+4*4    [[15,22]]

# (2,2) (2,2)  #앞의 행과 뒤의 열의 갯수가 같아야 한다.

[[1 2]
 [3 4]]


matrix([[ 7, 10],
        [15, 22]])

ndarray 에서 행렬곱 연산자 @이다.
python 재단에서 numpy를 위해 만들어준 연산자이다.   

행렬곱을 하기 위해서는 shape가 맞아야 한다.
T는 transpose(전치)의 약자이다.   

In [174]:
print(a)
print(a.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [175]:
print(a.T)
print(a.T.shape)

# (3,4)(4,2) => 결과 (3,2)
# (2,3)(3,5) => 결과 (2,5)
# (1000, 7) (7, 3) => 결과 (1000, 3)

[[0 3]
 [1 4]
 [2 5]]
(3, 2)


In [176]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

In [177]:
a= np.arange(1,17).reshape(1,16)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [178]:
print(a.shape)            # (1,16)
print(a.T.shape)          #(16,1)
a @ a.T                 # 결과 (1,1)

(1, 16)
(16, 1)


array([[1496]])

matrix는 * 와 @ 모두가 가능하다.

In [179]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

In [180]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

In [181]:
print(type(a))
np.dot(a, a.T)

<class 'numpy.ndarray'>


array([[1496]])

In [182]:
print(type(c))
np.dot(c, c.T)

<class 'numpy.matrix'>


matrix([[ 5, 11],
        [11, 25]])


* : matrix  
@ : matrix , adarray  
dot() : matrix, adarray   




method 방식으로 행렬곱 할 수 있다.   
function 방법과 사용하는 방법이 다르므로 주의한다.  

In [183]:
np. dot (c,c.T)

matrix([[ 5, 11],
        [11, 25]])

In [184]:
c.dot (c.T)

matrix([[ 5, 11],
        [11, 25]])

##strides

strides는 다음 원소끼리의 메모리크기를 차원별로 알려준다.   
C의 포인터 개념을 알고 있으면 이해하기가 쉽다.


In [185]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
# 행의 메모리 간격은 32 bytes
# 열의 메모리 간격은 8 bytes
a.strides

(32, 8)

In [187]:
a.itemsize

8

In [188]:
#열의 원소 갯수 * itemsize = 행의메모리간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

## axis
axis는 다차원 배열을 연산할때 기준이 되는 축이다.  

In [189]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [190]:
np.sum(a)

66

In [191]:
np.sum(a, axis=0) # a 배열은 2차원이므로 axis=0은 행기준 (행마다)
np.sum(a, axis=1)                       #axis=1은 열기준 (열마다)

array([ 6, 22, 38])

```
(0,0) (0,1) (0,2) (0,3)
(1,0) (0,1) (0,2) (1,3)
(2,0) (2,1) (2,2) (2,3)


```


In [192]:
a = np.arange(24).reshape(2,3,4) #2공간 3행 4열
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

```
(0,0,0) (0,0,1) (0,0,2) (0,0,3)
(0,1,0) (0,1,1) (0,1,2) (0,1,3)
(0,2,0) (0,2,1) (0,2,2) (0,2,3)

(1,0,0) (1,0,1) (1,0,2) (1,0,3)
(1,1,0) (1,1,1) (1,1,2) (1,1,3)
(1,2,0) (1,2,1) (1,2,2) (1,2,3)
```

In [193]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [194]:
np.sum(a)  #(2,3,4) => (1,)

276

In [195]:
np.sum(a, axis=0)    # #(2,3,4) => (3,4)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [196]:
np.sum(a, axis=1)  # #(2,3,4) => (2,4)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [197]:
np.sum(a, axis=2)  # #(2,3,4) => (2,3)

array([[ 6, 22, 38],
       [54, 70, 86]])

## array 모양 바꾸기


(1)reshape
reshape는 차원을 바꿔주는 기능을 한다.

In [198]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [199]:
b = a.reshape(3,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [200]:
#value error => 크기가 맞게 () 안의 숫자를 조정해줘야함
b= a.reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [201]:
# 음수를 쓰면 알아서 shape를 맞춘다
#음수값은 아무거나 상관없다 .
b = a.reshape(2,3,-1)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [202]:
b = a.reshape(2,3,-100)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [203]:
b = a.reshape(3,4,-1)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [204]:
b= a.reshape(3,-1,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

#resize

size의 원소개수를 알려준다

In [205]:
#mutable이다. return이 없고 자기 자신을 바꾼다.
#원래의 원소 개수와 변경하는 원소 개수가 안 맞아도 된다. (0으로 채워준다) => reshape와 차이점 2
a= np.arange(24)
print(a.size)
print(len(a))

24
24


In [206]:
#원래의 원소 개수보다 작으면 버린다.
b= np.arange(24)
b.resize(2,3,8)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

## array 쪼개기


split

In [212]:
a = np. arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [208]:
b= np.split(a,3, axis=0)  #축 : 0
print(b)
print(type(b))


[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

In [214]:
# 0부터 5 미만 인덱스
# 5이상 8 미만 인덱스
# 8이상 13미만 인덱스
#13이상 인덱스

np.split(a, [5, 8, 13])

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

hsplit & vsplit

In [216]:
a = np.arange(24)
b = a.reshape (4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [218]:
np.split(b,2, axis =0)  #b는 2차원이므로 axis= 0의 의미는 행이다.

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [219]:
# 2차원이므로 axis=1을 사용할 수 없다.
np.split(b, 2, axis=1) # b는 2차원이므로 axis =1의 의미는 열이다.

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [221]:
# vertical (수직)
np. vsplit(b,2)    #np.split(b,2 axis=0)과 같은결과

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [222]:
# horizental (수평)
np.hsplit(b,2)  # np split(b,2, axis=1)과 결과가 같음

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]